
# Base image
FROM python:3.10-slim

WORKDIR /app

# Install dependencies
COPY flask-app/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy app code
COPY flask-app/ .

EXPOSE 5000
CMD ["python", "app.py"]
